
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-16
owner: ucsb-cs156-f24
repo_name: team01-f24-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"JJ-Recommendation-Requests-create-db","number":44,"title":"Create DB for Recomendation Requests","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/44"},{"author":{"id":"U_kgDOBtnpoQ","is_bot":false,"login":"li-kelly","name":""},"headRefName":"kl-UCSBDiningCommonsMenuItem-create-db","number":43,"title":"ucsb dining commons menu item create db","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/43"}]
