
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-16
owner: ucsb-cs156-f24
repo_name: team01-f24-16
pull_requests: [{"author":{"id":"U_kgDOB3E0Rw","is_bot":false,"login":"ttnguyen908","name":"Tiffany Nguyen"},"headRefName":"Tiffany-HelpReq-ALL-and-POST","number":66,"title":"HelpRequest get (by ID) implementation tests now working! 100% jacoco and pitest testing.","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/66"},{"author":{"id":"U_kgDOB3D13A","is_bot":false,"login":"rohanpreetam","name":""},"headRefName":"rp-MenuItemReview-create-db","number":65,"title":"Create, ADD, and GET all completed","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/65"},{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"recReq_delete","number":63,"title":"recommendation request delete method and testing.","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/63"},{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"recReq_put","number":62,"title":"Put request implementation and testing coverage:","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/62"}]
