
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-16
owner: ucsb-cs156-f24
repo_name: team01-f24-16
pull_requests: [{"author":{"id":"U_kgDOB3D13A","is_bot":false,"login":"rohanpreetam","name":""},"headRefName":"rp-MenuItemReview-create-db","number":50,"title":"Added files for MenuItemReview database","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/50"},{"author":{"id":"U_kgDOB3Ckdw","is_bot":false,"login":"Salshriaan","name":""},"headRefName":"Salshriaan-readme-1","number":49,"title":"Update README.md (one more todo left)","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/49"},{"author":{"id":"U_kgDOBtnpoQ","is_bot":false,"login":"li-kelly","name":""},"headRefName":"kl-UCSBDiningCommonsMenuItem-create-controller","number":48,"title":"ucsbdiningcommonsmenuitem added GET index and POST (create)","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/48"}]
