
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-16
owner: ucsb-cs156-f24
repo_name: team01-f24-16
pull_requests: [{"author":{"id":"U_kgDOB3E0Rw","is_bot":false,"login":"ttnguyen908","name":"Tiffany Nguyen"},"headRefName":"Tiffany-HelpReq-DELETE","number":69,"title":"HelpRequest controller now has delete operation + passing jacoco and pitest 100%!","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/69"},{"author":{"id":"U_kgDOB3D13A","is_bot":false,"login":"rohanpreetam","name":""},"headRefName":"rp-MenuItemReview-create-db","number":68,"title":"Get controller tests completed","url":"https://github.com/ucsb-cs156-f24/team01-f24-16/pull/68"}]
